component: cdn
name: cdnDemo
org: orgDemo
app: appDemo
stage: dev

inputs:
  area: overseas
  domain: fullstack.yugasun.com
  origin:
    origins:
      - up6pwd9-89hm718-xxx.cos-website.ap-guangzhou.myqcloud.com
    originType: cos
    originPullProtocol: https
  serviceType: web
  forceRedirect:
    switch: on
    redirectType: https
    redirectStatusCode: 301
  https:
    switch: on
    http2: on
    certInfo:
      certId: 'Z67aCPcj'
      # certificate: 'xxx'
      # privateKey: 'xxx'
